title: Microservicio de autenticación
description: Documentación del microservicio que gestiona la autenticación de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/microservicio-autenticacion"
